corpus/urls.py
from django.conf.urls import patterns, url

from corpus import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^title/(?P<title_id>\w+)/$', views.show_title, name='get_title'),
    url(r'^author/(?P<author_id>\w+)/$', views.show_author, name='show_author'),
    url(r'^all_plays/$', views.show_all_plays, name='show_all_plays'),
    url(r'^trial_annotations/$', views.show_trial_annotations),
    url(r'^year/(?P<year>\w+)/$', views.show_year, name='show_year'),
    url(r'^genres/$', views.show_genres, name='show_genres'),
    url(r'^genre/(?P<genre_id>\w+)$', views.show_genre, name='show_genre'),
    url(r'^subgenre/(?P<genre_id>\w+)$', views.show_subgenre),
    url(r'^originals$', views.show_first_year_of_publication),
    url(r'^entity_stats/$', views.entity_statistics_for_corpus,
        name='entity_statistics_for_corpus'),
    url(r'^entity_stats/(?P<title_id>\w+)/$',
        views.entity_statistics_for_title, name='entity_statistics_for_title'),
    url(r'^subgenre_stats/$', views.subgenre_entity_statistics_for_corpus,
        name='subgenre_entity_statistics_for_corpus'),

    url(r'^titles$', views.TitleViewSet.as_view(), name='title-list'),
    url(r'^titles/(?P<pk>[\w]+)/$', views.TitleInstanceView.as_view(),
        name='title-instance'),
    url(r'^titles/(?P<pk>[\w]+)/wordcloud/$',
        views.title_wordcloud, name='title-wordcloud'),
)

embodied_emotions/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'embodied_emotions.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^corpus/', include('corpus.urls')),
    url(r'^entity_vis/', include('entity_vis.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

corpus/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class Auteur(models.Model):
    pers_id = models.CharField(primary_key=True, max_length=7)
    ppn = models.TextField(blank=True)
    ppn_oud = models.TextField(blank=True)
    achternaam = models.TextField(blank=True)
    voornaam = models.TextField(blank=True)
    voornaam_volledig = models.TextField(blank=True)
    alfabetiseer = models.TextField(blank=True)
    jaar_geboren = models.TextField(blank=True)
    jaar_overlijden = models.TextField(blank=True)
    geb_datum = models.TextField(blank=True)
    overl_datum = models.TextField(blank=True)
    geb_plaats = models.TextField(blank=True)
    overl_plaats = models.TextField(blank=True)
    lijfspreuk = models.TextField(blank=True)
    bntl_comment = models.TextField(blank=True)
    aanvullend = models.TextField(blank=True)
    lexicon = models.TextField(blank=True)
    taalcode = models.TextField(blank=True)
    taalcode_2 = models.TextField(blank=True)
    periode = models.TextField(blank=True)
    vrouw = models.TextField(blank=True)
    secundair = models.TextField(blank=True)
    letterkunde = models.TextField(blank=True)
    taalkunde = models.TextField(blank=True)
    geb_plaats_code = models.TextField(blank=True)
    geb_land_code = models.TextField(blank=True)
    overl_plaats_code = models.TextField(blank=True)
    overl_land_code = models.TextField(blank=True)
    voorvoegsel = models.TextField(blank=True)
    jeugdliteratuur = models.TextField(blank=True)
    suriname = models.TextField(blank=True)
    nonfictie = models.TextField(blank=True)
    nnbw = models.TextField(blank=True)
    nnbw_commentaar = models.TextField(blank=True)
    nnbw_deel = models.TextField(blank=True)
    nnbw_kolom = models.TextField(blank=True)
    ppn_ncc = models.TextField(blank=True)
    bio_portaal = models.TextField(blank=True)
    zuidafrika = models.TextField(blank=True)
    fries = models.TextField(blank=True)
    limburg = models.TextField(blank=True)
    buitenland = models.TextField(blank=True)
    auteursactie = models.TextField(blank=True)
    alias = models.TextField(blank=True)
    nlab = models.TextField(blank=True)
    class Meta:
        db_table = 'auteur'


    def __unicode__(self):
        return '{voornaam} {achternaam}'.format(voornaam=self.voornaam,
                                                achternaam=self.achternaam)

class Auteurxberoep(models.Model):
    pers_id = models.CharField(max_length=7, blank=True)
    beroep_id = models.CharField(max_length=2, blank=True)
    id = models.CharField(primary_key=True, max_length=5)
    class Meta:
        db_table = 'auteurxberoep'

class Auteurxorganisatie(models.Model):
    id = models.CharField(primary_key=True, max_length=3)
    pers_id = models.CharField(max_length=7, blank=True)
    dbnl_orga_id = models.CharField(max_length=14, blank=True)
    class Meta:
        db_table = 'auteurxorganisatie'

class Beeld(models.Model):
    id = models.CharField(primary_key=True, max_length=4)
    bestandsnaam = models.TextField(blank=True)
    ti_id = models.CharField(max_length=15, blank=True)
    omschrijving = models.TextField(blank=True)
    medium = models.TextField(blank=True)
    maker = models.TextField(blank=True)
    datering = models.TextField(blank=True)
    herkomst = models.TextField(blank=True)
    bron = models.TextField(blank=True)
    onderschrift = models.TextField(blank=True)
    trefwoorden = models.TextField(blank=True)
    rechten = models.TextField(blank=True)
    sortering = models.TextField(blank=True)
    pagina = models.TextField(blank=True)
    class Meta:
        db_table = 'beeld'

class Beroep(models.Model):
    beroep_id = models.CharField(primary_key=True, max_length=2)
    omschrijving = models.TextField(blank=True)
    class Meta:
        db_table = 'beroep'

class Genre(models.Model):
    genre_id = models.CharField(primary_key=True, max_length=2)
    genre = models.TextField(blank=True)
    order = models.TextField(blank=True)
    class Meta:
        db_table = 'genre'


    def __unicode__(self):
        return self.genre

class Landen(models.Model):
    land_id = models.CharField(primary_key=True, max_length=7)
    iso3166 = models.TextField(blank=True)
    exoniem_landnaam = models.TextField(blank=True)
    exoniem_officielenaam = models.TextField(blank=True)
    exoniem_hoofdstad = models.TextField(blank=True)
    exoniem_inwoneraanduiding = models.TextField(blank=True)
    exoniem_bijvnw = models.TextField(blank=True)
    endoniem_landnaam = models.TextField(blank=True)
    endoniem_officieel = models.TextField(blank=True)
    endoniem_hoofdstad = models.TextField(blank=True)
    opmerkingen = models.TextField(blank=True)
    naamsvariant = models.TextField(blank=True)
    class Meta:
        db_table = 'landen'

class Landxwerelddeel(models.Model):
    land_id = models.CharField(max_length=7)
    werelddeel_id = models.TextField(blank=True)
    class Meta:
        db_table = 'landxwerelddeel'

class Naamsvariant(models.Model):
    id = models.CharField(primary_key=True, max_length=5)
    pers_id = models.CharField(max_length=7, blank=True)
    achternaam = models.TextField(blank=True)
    voornaam = models.TextField(blank=True)
    voorvoegsel = models.TextField(blank=True)
    class Meta:
        db_table = 'naamsvariant'

class Organisatie(models.Model):
    dbnl_orga_id = models.CharField(primary_key=True, max_length=14)
    stad_dorp = models.TextField(db_column='Stad/dorp', blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    kamer = models.TextField(db_column='Kamer', blank=True) # Field name made lowercase.
    topo_id = models.TextField(blank=True)
    herkomst = models.TextField(blank=True)
    stichtingsdatum = models.TextField(db_column='Stichtingsdatum', blank=True) # Field name made lowercase.
    stichtingsjaar = models.TextField(db_column='Stichtingsjaar', blank=True) # Field name made lowercase.
    gestandariseerde_naam = models.TextField(db_column='Gestandariseerde naam', blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    varianten = models.TextField(db_column='Varianten', blank=True) # Field name made lowercase.
    opheffingsdatum = models.TextField(blank=True)
    opheffingsjaar = models.TextField(blank=True)
    org_id = models.TextField(blank=True)
    voorvoegsel = models.TextField(blank=True)
    buitenland = models.TextField(blank=True)
    class Meta:
        db_table = 'organisatie'

class Subgenre(models.Model):
    subgenre = models.TextField(blank=True)
    subgenre_id = models.CharField(primary_key=True, max_length=5)
    order = models.TextField(blank=True)
    class Meta:
        db_table = 'subgenre'
    
    
    def __unicode__(self):
        return self.subgenre

class Titel(models.Model):
    ti_id = models.CharField(primary_key=True, max_length=14)
    auteurs = models.ManyToManyField(Auteur, through='Titelxauteur')
    genres = models.ManyToManyField(Genre, through='Titelxgenre')
    subgenres = models.ManyToManyField(Subgenre, through='Titelxsubgenre')
    contains = models.ManyToManyField('Titel',
                                      through='TitelBevat',
                                      related_name='parent_ti_id')
    pers_id_bk = models.CharField(max_length=7, blank=True)
    koepel_id = models.CharField(max_length=14, blank=True)
    kop_borkv_bk = models.TextField(blank=True)
    titel = models.TextField(blank=True)
    subtitel = models.TextField(blank=True)
    jaar = models.TextField(blank=True)
    druk = models.TextField(blank=True)
    vols = models.TextField(blank=True)
    uitgever = models.TextField(blank=True)
    pica_info = models.TextField(blank=True)
    borkv = models.TextField(blank=True)
    genre_bk = models.TextField(blank=True)
    genre2_bk = models.TextField(blank=True)
    subgenre = models.TextField(blank=True)
    geplaatst = models.TextField(blank=True)
    categorie = models.TextField(blank=True)
    bundelcode = models.TextField(blank=True)
    duizend = models.TextField(blank=True)
    duizend_jeugd = models.TextField(blank=True)
    scan_pagina = models.TextField(blank=True)
    scan_opmerkingen = models.TextField(blank=True)
    scan_start = models.TextField(blank=True)
    partner = models.TextField(blank=True)
    scancode = models.TextField(blank=True)
    batch = models.TextField(blank=True)
    mag_op_site = models.TextField(blank=True)
    verdacht_beeld = models.TextField(blank=True)
    x_verdacht_beeld_oud = models.TextField(blank=True)
    ppn = models.TextField(blank=True)
    signatuur = models.TextField(blank=True)
    bibliotheek = models.TextField(blank=True)
    duizend_signatuur = models.TextField(blank=True)
    duizend_complement = models.TextField(blank=True)
    duizend_romans = models.TextField(blank=True)
    dsol = models.TextField(blank=True)
    vlaams_klassiek = models.TextField(blank=True)
    limburg = models.TextField(blank=True)
    taalcode = models.TextField(blank=True)
    closed_domain = models.TextField(blank=True)
    number_2008_2012 = models.TextField(db_column='2008-2012', blank=True) # Field renamed to remove unsuitable characters. Field renamed because it wasn't a valid Python identifier.
    number_2008_2012_syn = models.TextField(db_column='2008-2012-syn', blank=True) # Field renamed to remove unsuitable characters. Field renamed because it wasn't a valid Python identifier.

corpus/templates/corpus/author.html
{% load corpus_extras %}
<h1>{{ author.voornaam }} {{ author.achternaam }}</h1>

<p>Geboren: {{ author.geb_datum }} {{ author.jaar_geboren }}</p>
<p>Overleden: {{ author.overl_datum }} {{ author.jaar_overlijden }}</p>
<p>Titels
    <ul>
        {% for title in author.titel_set.all %}
        <li>
            {% title_link title %} -
            {% year_link title.jaar %}    
        </li>
        {% endfor %}
    </ul>
</p>

corpus/templates/corpus/genres.html
{% extends "base.html" %}
{% load staticfiles %}
{% load corpus_extras %}

{% block title %}Embodied emotions: genres{% endblock %}

{% block content %}
<h1>Genres in het corpus</h1>
<p>Totaal in corpus: {{ total_titles }} titels.</p>
<h2>Genres</h2>
{% if genres %}
    <ol>
        {% for genre in genres %}
            <li>
                {% genre_link genre %}:
                {{ genre.num_titles }} titels
            </li>
        {% endfor %}
    </ol>
{% else %}
    <p>Geen genres gevonden.</p>
{% endif %}
<div class="genre_histogram"></div>
<script type="text/javascript">
     var json_plays = {{ genre_histogram|safe }};

    stackedBarChart(json_plays, '.genre_histogram');
</script>
<h2>Subgenres</h2>
{% if subgenres %}
    <ol>
        {% for genre in subgenres %}
            <li>
                {% subgenre_link genre %}:
                {{ genre.num_titles }} titels
            </li>
        {% endfor %}
    </ol>
{% else %}
    <p>Geen subgenres gevonden.</p>
{% endif %}
<div class="subgenre_histogram"></div>
<script type="text/javascript">
     var json_plays = {{ subgenre_histogram|safe }};

    stackedBarChart(json_plays, '.subgenre_histogram');
</script>
{% endblock %}

corpus/templates/corpus/plays.html
{% extends 'base.html' %}
{% load corpus_extras %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<h1>{{ page_title }}</h1>
{% if corpus %}
    <ul>
        {% for play in corpus %}
        <li>
            {% year_link play.jaar %} - 
            {% title_link play %} - 
            {% for auteur in play.auteurs.all %}
                {% author_link auteur %}
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No plays in corpus.</p>
{% endif %}
{% endblock %}

corpus/templates/corpus/playscontain.html
{% load corpus_extras %}
<h1>{{ page_title }}</h1>
{% if corpus %}
    <table border="1">
        <tr>
            <th>Titel in corpus</th>
            <th>Bevat</th>
        </tr>
        {% for play in corpus %}
            {% if play.contains.all %}
                {% for original in play.contains.all %}
                    <tr>
                        <td>
                            {% year_link play.jaar %} - 
                            {% title_link play %} - 
                            {% for auteur in play.auteurs.all %}
                                {% author_link auteur %}
                            {% endfor %}
                        </td>
                        <td>
                            {{ original.jaar }} - 
                            {{ original.titel }} 
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        {% year_link play.jaar %} - 
                        {% title_link play %} - 
                        {% for auteur in play.auteurs.all %}
                            {% author_link auteur %}
                        {% endfor %}
                    </td>
                    <td>
                        <br/>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% else %}
    <p>No plays in corpus.</p>
{% endif %}

corpus/templates/corpus/title.html
{% extends 'base.html' %}
{% load corpus_extras %}

{% block title %}{{ title.titel }}{% endblock %}

{% block content %}
<h1>{{ title.titel }}</h1>
<p>Door:
    {% for author in title.auteurs.all %}
        {% author_link author %} </br>
    {% endfor %}
</p>

<p>Jaar: {% year_link title.jaar %} 
</p>

<p>
    Genre:
    {% for genre in title.genres.all %}
        {% genre_link genre %} </br>
    {% endfor %}
</p>

<p>
    Subgenre:
    {% for subgenre in title.subgenres.all %}
        {% subgenre_link subgenre %} </br>
    {% endfor %}
</p>

<div ng-show="statistics">
    <h2>Statistics</h2>
    <p ng-repeat="stats in statistics">
        {% verbatim %}
            # words: {{ stats.num_words }}
            # {{ stats.category }} words: {{ stats.num_cat }}
            Percentage {{ stats.category }}: {{ stats.percentage }}
        {% endverbatim %}
    </p>
{% endblock %}

corpus/templates/corpus/year.html
{% load corpus_extras %}
<h1>Toneelstukken uit {{ year }}</h1>

{% if corpus %}
    <ul>
        {% for title in corpus %}
            <li> {% title_link title %} </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Geen toneelstukken in corpus.</p>
{% endif %}