corpus/urls.py
from django.conf.urls import patterns, url

from corpus import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^title/(?P<title_id>\w+)/$', views.show_title, name='get_title'),
    url(r'^author/(?P<author_id>\w+)/$', views.show_author, name='show_author'),
    url(r'^all_plays/$', views.show_all_plays, name='show_all_plays'),
    url(r'^trial_annotations/$', views.show_trial_annotations),
    url(r'^year/(?P<year>\w+)/$', views.show_year, name='show_year'),
    url(r'^genres/$', views.show_genres, name='show_genres'),
    url(r'^genre/(?P<genre_id>\w+)$', views.show_genre, name='show_genre'),
    url(r'^subgenre/(?P<genre_id>\w+)$', views.show_subgenre),
    url(r'^originals$', views.show_first_year_of_publication),
    url(r'^entity_stats/$', views.entity_statistics_for_corpus,
        name='entity_statistics_for_corpus'),
    url(r'^entity_stats/(?P<title_id>\w+)/$',
        views.entity_statistics_for_title, name='entity_statistics_for_title'),
    url(r'^subgenre_stats/$', views.subgenre_entity_statistics_for_corpus,
        name='subgenre_entity_statistics_for_corpus'),

    url(r'^titles$', views.TitleViewSet.as_view(), name='title-list'),
    url(r'^titles/(?P<pk>[\w]+)/$', views.TitleInstanceView.as_view(),
        name='title-instance'),
    url(r'^titles/(?P<pk>[\w]+)/wordcloud/$',
        views.title_wordcloud, name='title-wordcloud'),
)

embodied_emotions/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'embodied_emotions.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^corpus/', include('corpus.urls')),
    url(r'^entity_vis/', include('entity_vis.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

entity_vis/urls.py
from django.conf.urls import patterns, url

from entity_vis import views

urlpatterns = patterns(
    '',
    url(r'^entity_graph_title/(?P<title_id>\w+)/$', views.entities_in_play,
        name='entities_in_play'),
    url(r'^entity_words$', views.entity_words, name='entity_words'),
    url(r'^speakingturns/(?P<concept>\w+)/$', views.find_in_speakingturns,
        name='find_in_speakingturns'),
    url(r'^entity_word_pairs$', views.entity_word_pairs,
        name='entity_word_pairs'),
    url(r'^browse_entities$', views.browse_entities, name='browse_entities'),
    url(r'^entity_categories$', views.entity_categories,
        name='entity_categories'),
    url(r'^subgenres_stats_time/$', views.subgenres_stats_time,
        name='subgenres_stats_time'),
)

entity_vis/models.py
from django.db import models

class Entity(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class EntityValue(models.Model):
    name = models.CharField(max_length=140)

    def __unicode__(self):
        return self.name

class EntityScore(models.Model):
    speakingturn = models.ForeignKey('SpeakingTurn')
    entity = models.ForeignKey(Entity)
    entityvalues = models.ManyToManyField(EntityValue)
    score = models.IntegerField()

    def __unicode__(self):
        return '{}: {} - {}'.format(self.speakingturn,
                                    self.entity.name,
                                    self.score)

class Character(models.Model):
    name = models.CharField(max_length=50)
    play = models.ForeignKey('corpus.Titel')
    num_speaking_turns = models.IntegerField()

    def __unicode__(self):
        return '{} ({})'.format(self.name, self.play.titel)

class SpeakingTurn(models.Model):
    character = models.ForeignKey(Character)
    order = models.IntegerField()
    entity = models.ManyToManyField(Entity, through=EntityScore)

    def __unicode__(self):
        return '({}) {}'.format(self.order,
                                      self.character)

entity_vis/views.py
import json
from elasticsearch import Elasticsearch

from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.http import JsonResponse

from corpus.models import Titel
from entity_vis.models import Character, EntityScore, SpeakingTurn
from entity_vis.entitysc import get_r_score, moving_average
from entity_vis.es import search_query, term_query, doc_count, match_all
from embodied_emotions.utils import get_from_body

def entities_in_play(request, title_id):
    # angular sends post data in the request.body
    if request.body:
        categories = json.loads(request.body).get('categories')
    else:
        categories = []

    if len(categories) < 2:
        return JsonResponse([], safe=False)

    entity_cat1 = categories[0]
    entity_cat2 = categories[1]

    entity_type = 'liwc'

    q = term_query('text_id', title_id)

    # doc count
    num_results = doc_count(q, 'event')

    # characters
    q = term_query('text_id', title_id, num_results)
    q["sort"] = [{"order": {"order": "asc"}}]
    q["aggs"] = {
        "characters": {
            "terms": {
                "field": "actor",
                "size": 5
            }
        }
    }
    result = search_query(q, 'event')

    data = []

    characters = result.get('aggregations').get('characters').get('buckets')
    for character in characters:
        name = character.get('key')
        values = []
        for hit in result.get('hits').get('hits'):
            field = '{}-entities'.format(entity_type)
            entity_data1 = hit.get('_source').get(field).get('data') \
                              .get(entity_cat1, [])
            entity_data2 = hit.get('_source').get(field).get('data') \
                              .get(entity_cat2, [])
            char = hit.get('_source').get('actor')
            turn = hit.get('_source').get('order')
            if char == name and entity_data1:
                score1 = len(entity_data1)
            else:
                score1 = 0

            if char == name and entity_data2:
                score2 = len(entity_data2)
            else:
                score2 = 0
            score = get_r_score(score1, score2)
            values.append(score)

        # smoothing
        scores = moving_average(values, 10).tolist()

        values = []
        turn = 1
        for sc in scores:
            values.append({'turn': turn, 'Score': sc})
            turn += 1

        data.append({'key': name, 'values': values})

    return JsonResponse(data, safe=False)


def subgenres_stats_time(request):
    """Return data to draw subgenres over time for all categories.

    Returns
    -------
    data : dict
        The keys in data are the selected entity categories.
        The values are an array of dicts (each dict provides the data about a
        subgenre):
        {
            'key': 'subgenre name',
            'values': [{
                'x': x-value,
                'y': y-value
            }, ...]
        }
    """
    categories = get_from_body(request, 'categories')

    data = {}
    for cat in categories:
        # number of years in a bucket
        interval = 20

        q = match_all()
        q["aggs"] = {
            "subgenres": {
                "terms": {
                    "field": "subgenre",
                    "size": 100
                },
                "aggs": {
                    "subgenre-year": {
                        "histogram": {
                            "field": "year",
                            "interval": interval,
                            "min_doc_count": 0,
                            "extended_bounds": {
                                "min": 1600,
                                "max": 1850
                            }
                        },
                        "aggs": {
                            "entities": {
                                "value_count": {
                                    "field": "liwc-entities.data.{}"
                                             .format(cat)
                                }
                            },
                            "num_words": {
                                "sum": {
                                    "field": "num_words"
                                }
                            }
                        }
                    }
                }
            }
        }

        result = search_query(q, 'event')

        # format output according to what is expected by nvd3
        graph_data = []
        subgenre_result = result.get('aggregations').get('subgenres') \
                                .get('buckets')
        for subgenre_data in subgenre_result:
            subgenre = subgenre_data.get('key')
            values = []
            for year_data in subgenre_data.get('subgenre-year').get('buckets'):
                year = year_data.get('key')
                num_entities = year_data.get('entities').get('value')
                num_words = year_data.get('num_words').get('value')
                if num_words > 0:
                    percentage = num_entities/num_words * 100.0
                else:
                    percentage = 0.0
                values.append({'x': year, 'y': percentage})
            graph_data.append({'key': subgenre, 'values': values})
        data[cat] = graph_data

    return JsonResponse(data, safe=False)


def browse_entities(request):
    context = {}
    return render(request, 'entity_vis/browse_entities.html', context)


def entity_words(request):
    categories = request.GET.get('categories', '')
    if not categories:
        categories = []
    else:
        categories = categories.split(',')

    entity_words = {}
    ew_year = {}
    ew_genre = {}
    ew_genre_year = {}
    num_texts = 0
    num_entities = 50

    for cat in categories:
        print cat
        q = {
            "query": {
                "match_all": {}
            },
            "size": 0,
            "aggregations": {
                cat: {
                    "terms": {
                        "field": "liwc-entities.data.{}".format(cat),
                        "size": 1000
                    }
                },
                "num_texts": {
                    "cardinality": {
                        "field": "text_id"
                    }
                },
                "entities-year": {
                    "histogram": {
                        "field": "year",
                        "interval": 10,
                        "min_doc_count": 0,
                        "extended_bounds": {
                            "min": 1600,
                            "max": 1850
                        }
                    },
                    "aggs": {
                        "entity": {
                            "terms": {
                                "field": "liwc-entities.data.{}".format(cat),
                                "size": num_entities
                            }
                        },
                        "texts": {
                            "cardinality": {
                                "field": "text_id"
                            }
                        },

                    }
                },
                "entities-genre": {
                    "terms": {
                        "field": "subgenre",
                        "size": 100
                    },
                    "aggs": {
                        "entity": {
                            "terms": {
                                "field": "liwc-entities.data.{}".format(cat),
                                "size": num_entities
                            }
                        },
                        "texts": {
                            "cardinality": {
                                "field": "text_id"
                            }
                        }
                    }
                },
                "subgenre": {
                    "terms": {
                        "field": "subgenre",
                        "size": 25
                    },
                    "aggs": {
                        "year": {
                            "histogram": {
                                "field": "year",
                                "interval": 10,
                                "min_doc_count": 0,
                                "extended_bounds": {
                                    "min": 1600,
                                    "max": 1850
                                }
                            },
                            "aggs": {
                                "entity": {
                                    "terms": {
                                        "field": "liwc-entities.data.{}"
                                                 .format(cat),
                                        "size": num_entities,
                                    }
                                },
                                "texts": {
                                    "cardinality": {
                                        "field": "text_id"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        result = search_query(q, 'event')
        entity_words[cat] = result.get('aggregations').get(cat).get('buckets')
        num_texts = int(result.get('aggregations').get('num_texts')
                              .get('value'))
        ew_genre[cat] = result.get('aggregations').get('entities-genre') \
                              .get('buckets')
        ew_year[cat] = result.get('aggregations').get('entities-year') \
                             .get('buckets')
        ew_genre_year[cat] = result.get('aggregations').get('subgenre') \
                                   .get('buckets')
    context = {
        'entity_words': entity_words,

entity_vis/templates/entity_vis/browse_entities.html
{% extends 'base.html' %}
{% load corpus_extras %}

{% block title %}Browse entities{% endblock %}

entity_vis/templates/entity_vis/entitywords.html
{% load staticfiles %}
<html>
    <head>
        <title>Entity Words</title>
    </head>

    <body>
    <h1>Entity Words</h1>

    <h2>Frequency in corpus ({{ num_texts }} texts)</h2>
    {% for category, values in entity_words.items %}
        <table border="1" style="float: left">
            <tr>
                <th>{{ category }}</th><th>Frequency</th>
            </tr>
            {% for v in values|slice:":50" %}
                <tr>
                    <td>{{ v.key }}</td>
                    <td>{{ v.doc_count }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}
    <div style="clear:both;"></div>

    <h2>Entities per year</h2>
    {% for category, values in ew_year.items %}
        <h3>{{ category }}</h3>
        {% for v in values %}
            <table border="1" style="float: left">
                <th colspan="2">{{ v.key }} ({{ v.texts.value }})</th>
                {% for b in v.entity.buckets %}
                    <tr>
                        <td>{{ b.key }}</td><td>{{ b.doc_count }}</td>
                    </tr>
                {% empty %}
                    {% for i in range %}
                        <tr>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
        {% endfor %}
        <div style="clear:both;"></div>
    {% endfor %}
    
    <h2>Entities per genre</h2>
    {% for category, values in ew_genre.items %}
        <h3>{{ category }}</h3>
        {% for v in values %}
            <table border="1" style="float: left">
                <th colspan="2">{{ v.key }} ({{ v.texts.value }})</th>
                {% for b in v.entity.buckets %}
                    <tr>
                        <td>{{ b.key }}</td><td>{{ b.doc_count }}</td>
                    </tr>
                {% empty %}
                    {% for i in range %}
                        <tr>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
        {% endfor %}
        <div style="clear:both;"></div>
    {% endfor %}
    
    <h2>Entities per genre per year</h2>
    {% for category, values in ew_genre_year.items %}
        <h3>{{ category }}</h3>
        {% for genre_data in values %}
            <h4>{{ genre_data.key }}</h4>
            {% for year_data in genre_data.year.buckets %}
                <table border="1" style="float: left">
                    <tr>
                        <th colspan="2">{{ year_data.key }} ({{ year_data.texts.value }})</th>
                    </tr>
                    {% for e in year_data.entity.buckets %}
                        <tr>
                            <td>{{ e.key }}</td><td>{{ e.doc_count }}</td>
                        </tr>
                    {% empty %}
                        {% for i in range %}
                            <tr>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </table>
            {% endfor %}
            <div style="clear:both;"></div>
        {% endfor %}
    {% endfor %}
    </body>
</html>

entity_vis/templates/entity_vis/index.html
{% load staticfiles %}
<html>
    <head>
        <title>Visualisatie :: {{ title }}</title>

        <style>

            body {
                font: 10px sans-serif;
            }

            .axis path,
            .axis line {
                fill: none;
                stroke: #000;
                shape-rendering: crispEdges;
            }

            .x.axis path {
                display: none;
            }

            .line {
                fill: none;
                stroke: steelblue;
                stroke-width: 1.5px;
            }

            .legend rect {
                fill:white;
                stroke:black;
                opacity:0.8;
            }


        </style>

        <script type="text/javascript" src="{% static 'd3/d3.min.js'%}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static 'js/d3.legend.js'%}" charset="utf-8"></script>
    </head>

    <body>
    <h1>{{ title }} ({{ year }})</h1>
        <p>
            Auteur(s): {{ authors|join:", " }} </br>
            Genre(s): {{ genres|join:", " }} </br>
            Subgenre(s): {{ subgenres|join:", " }} </br>
        </p>
        <script>

            var margin = {top: 20, right: 20, bottom: 30, left: 50},
                width = 1500 - margin.left - margin.right,
                height = 500 - margin.top - margin.bottom;

            var x = d3.scale.linear()
                .range([0, width]);

            var y = d3.scale.linear()
                .range([height, 0]);

            var color = d3.scale.category10();

            var xAxis = d3.svg.axis()
                .scale(x)
                .tickValues([1, 89, 154, 230, 304])
                .orient("bottom");

            var yAxis = d3.svg.axis()
                .scale(y)
                .orient("left");

            var line = d3.svg.line()
                .x(function(d) { return x(d.Turn); })
                .y(function(d) { return y(d.score); });

            var svg = d3.select("body").append("svg")
                .attr("width", width + margin.left + margin.right)
                .attr("height", height + margin.top + margin.bottom)
             .append("g")
                .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

            var data = {{ data|safe }};
            console.log(data)

            x.domain([
                d3.min(data, function(c) { return d3.min(c.values, function(v){ return v.Turn; }); }),
                d3.max(data, function(c) { return d3.max(c.values, function(v){ return v.Turn; }); })
            ]);
            y.domain([
                d3.min(data, function(c) { return d3.min(c.values, function(v) { return v.score; }); }),
                d3.max(data, function(c) { return d3.max(c.values, function(v) { return v.score; }); })
            ]);

            svg.append("g")
                .attr("class", "x axis")
                .attr("transform", "translate(0," + height + ")")
                .call(xAxis);

            svg.append("g")
                .attr("class", "y axis")
                .call(yAxis)
              .append("text")
                .attr("transform", "rotate(-90)")
                .attr("y", 6)
                .attr("dy", ".71em")
                .style("text-anchor", "end")
                .text("score");

            var liwc_cat = svg.selectAll(".liwc")
                .data(data)
              .enter().append("g")
                .attr("class", "liwc");

            liwc_cat.append("path")
                .attr("class", "line")
                .attr("d", function(d) { return line(d.values); })
                .attr("data-legend", function(d) { return d.name; })
                .style("stroke", function(d) { return color(d.name); });

            liwc_cat.append("text")
                .datum(function(d) { return {name: d.name, value: d.values[d.values.length - 1]}; })
                .attr("transform", function(d) { return "translate(" + x(d.value.Turn) + "," + y(d.value.score) + ")"; })
                .attr("x", 3)
                .attr("dy", ".35em")
                .text(function(d) { return d.name; });
            
            legend = svg.append("g")
                .attr("class","legend")
                .attr("transform","translate(30,15)")
                .call(d3.legend)

        </script>

        <table border="1">
            <tr>
                <td>#</td>
                <td>Personage</td>
                <td>liwc-Posemo</td>
                <td>liwc-Negemo</td>
            </tr>

            {% for sp in speakingturns %}
                <tr>
                    <td>{{ sp.order }}</td>
                    <td>{{ sp.character.name }}</td>
                    <td>
                        {% for e in sp.entityscore_set.all %}
                            {% if e.entity.name == 'liwc-Posemo' %}
                                {{ e.entityvalues.all|join:'<br>' }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for e in sp.entityscore_set.all %}
                            {% if e.entity.name == 'liwc-Negemo' %}
                                {{ e.entityvalues.all|join:'<br>' }}
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}

    </body>
</html>

entity_vis/templates/entity_vis/speakingturns.html
{% load staticfiles %}
<html>
    <head>
        <title>Concept :: {{ concept }}</title>
    </head>

    <body>
    <h1>{{ title }}</h1>
    
    <h2>Aantal resultaten</h2>
    <p>Aantal speakingturns per woord waarop gezocht is.</p>
    <table border="1">
        <tr><th>Woord</th><th>gevonden in # speakingturns</th></tr>
        {% for word in doc_counts %}
            <tr>
                <td>{{ word.word }}</td>
                <td>{{ word.count }}</td>
            </tr>
        {% endfor %}
    </table>
    
    <h2>Gevonden speakingturns</h2>
    <table border="1">
        <tr>
            <th>Jaar</th>
            <th>Toneelstuk</th>
            <th>Spreker</th>
            <th>Tekst</th>
        </tr>
        {% for sp in speakingturns %}
            <tr>
                <td>{{ sp.year }}</td>
                <td>{{ sp.title }}</td>
                <td>{{ sp.actor }}</td>
                <td>{{ sp.text }}</td>
            </tr>
        {% endfor %}
    </table>

    <h2>Woordfrequenties</h2>
    <p>100 meest voorkomende woorden in de gevonden speakingturns.</p>
    <table border="1">
        <tr>
            <th>Woord</th>
            <th>Aantal</th>
        </tr>
        {% for word in word_frequencies %}
            <tr>
                <td>{{ word.key }}</td>
                <td>{{ word.doc_count }}</td>
            </tr>
        {% endfor %}
    </table>
    </body>
</html>